apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    project: expense
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      project: expense
      tier: web
  template:
    metadata:
      name: nginxfe-pod
      labels:
        app: frontend
        project: expense
        tier: web
    spec:
      containers:
      - name: frontend
        image: sankarjuvva/frontend:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 110m
            memory: 130Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector: 
    app: frontend
    project: expense
    tier: web
  ports:
    - name: service-port
      protocol: TCP
      port: 80
      targetPort: 80
