apiVersion: v1
kind: ConfigMap
metadata:
  name: bcconfmap
  namespace: expense
  annotations:
    buildurl: "https://hub.docker.com/"
  labels:
    project: expense
    module: backend
data:
 DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    project: expense
    tier: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      project: expense
      tier: api
  template:
    metadata:
       name: nginxbc-pod
       labels:
        app: backend
        project: expense
        tier: api
    spec:
      containers:
      - name: backend
        image: sankarjuvva/backend:latest
        envFrom:
        - configMapRef:
            name: bcconfmap
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector: 
    app: backend
    project: expense
    tier: api
  ports:
    - name: service-port
      protocol: TCP
      port: 8080
      targetPort: 8080
